# Generated by Django 3.1.2 on 2020-10-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.IntegerField(primary_key=True, serialize=False)),
                ('exam_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=200)),
                ('user_grade', models.IntegerField()),
                ('user_group', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
