# Generated by Django 3.1.2 on 2020-10-20 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201020_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('question_text', models.CharField(max_length=200)),
                ('user_answers', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=200)),
                ('exam_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.exam')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_info')),
            ],
        ),
    ]
