# Generated by Django 3.1.2 on 2020-10-20 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
