# Generated by Django 3.1.2 on 2020-10-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questions',
            name='exam_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user_answer',
            name='exam_id',
            field=models.IntegerField(default=1),
        ),
    ]
