# Generated by Django 3.1.2 on 2020-10-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201021_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='mobile',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_group',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
