# Generated by Django 3.1.2 on 2020-10-21 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201021_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='user_group',
        ),
    ]
