# Generated by Django 3.1.2 on 2020-10-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_user_info_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_id',
            field=models.CharField(max_length=300, primary_key=True, serialize=False, unique=True),
        ),
    ]
