# Generated by Django 3.1.2 on 2020-10-21 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201021_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_info',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_num', models.IntegerField(default=0)),
                ('grade_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='grade',
            fields=[
                ('grade_num', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.AlterField(
            model_name='questions',
            name='exam_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exam_info'),
        ),
    ]
