# Generated by Django 3.1.2 on 2020-10-21 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201021_2241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='grade',
        ),
    ]
