# Generated by Django 3.1.2 on 2020-10-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='submitted_user',
            fields=[
                ('exam_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=300)),
                ('submit', models.BooleanField(default=False)),
            ],
        ),
    ]
