# Generated by Django 3.1.2 on 2020-10-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
