# Generated by Django 3.1.2 on 2020-10-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_questions_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitted_user',
            name='submit',
        ),
        migrations.AddField(
            model_name='submitted_user',
            name='user_score',
            field=models.IntegerField(default=0),
        ),
    ]
