# Generated by Django 3.1.2 on 2020-10-26 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201026_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitted_user',
            name='user_score',
        ),
        migrations.CreateModel(
            name='user_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_score', models.IntegerField(default=0)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exam_info')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_info')),
            ],
        ),
    ]
