# Generated by Django 3.1.2 on 2020-10-27 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201026_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_score',
            old_name='user_score',
            new_name='score',
        ),
    ]
