# Generated by Django 3.1.2 on 2020-10-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20201030_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_answer',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
