# Generated by Django 3.1.2 on 2020-10-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_user_answer_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_info',
            name='total_score',
            field=models.IntegerField(default=10),
        ),
    ]
