# Generated by Django 3.1.2 on 2020-11-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_exam_info_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='coorect_way',
            field=models.TextField(default=''),
        ),
    ]
