# Generated by Django 3.1.2 on 2020-11-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_questions_coorect_way'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_answer',
            name='correct_way_toSolve',
            field=models.TextField(default='', null=True),
        ),
    ]
