# Generated by Django 3.1.2 on 2020-11-05 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_user_answer_correct_way_tosolve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='last_name',
        ),
    ]
