# Generated by Django 3.1.2 on 2020-11-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_user_info_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_info',
            name='grade_num',
            field=models.CharField(default='', max_length=300),
        ),
    ]
