# Generated by Django 3.1.2 on 2020-11-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20201106_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_grade',
            field=models.CharField(default='', max_length=300),
        ),
    ]
