# Generated by Django 3.1.2 on 2020-11-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20201106_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_text',
            field=models.TextField(default='', null=True),
        ),
    ]
